name: flutter_bloc_todo
description: A Todo List application using Flutter and BLoC pattern
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # BLoC State Management
  flutter_bloc: ^8.1.3

  # Value Equality
  equatable: ^2.0.5

  # Local Storage
  shared_preferences: ^2.2.2

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.1

  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
